# Generated by Django 6.0.7 on 2026-07-12 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offices', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='laundryoffice',
            name='subscription_tier',
            field=models.CharField(choices=[('free', 'Free'), ('starter', 'Starter'), ('pro', 'Pro'), ('premium', 'Premium')], default='free', max_length=20),
        ),
    ]
