# Generated by Django 6.0.7 on 2026-07-13 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offices', '0002_alter_laundryoffice_subscription_tier'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='branches',
            field=models.ManyToManyField(blank=True, related_name='branch_users', to='offices.laundryoffice'),
        ),
    ]
