# Generated by Django 6.0.7 on 2026-08-07 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offices', '0004_passwordresetotp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='laundryoffice',
            name='subscription_tier',
            field=models.CharField(choices=[('free', 'Free'), ('starter', 'Starter'), ('pro', 'Pro'), ('premium', 'Premium')], db_index=True, default='free', max_length=20),
        ),
        migrations.AlterField(
            model_name='passwordresetotp',
            name='email',
            field=models.EmailField(db_index=True, max_length=254),
        ),
        migrations.AlterField(
            model_name='passwordresetotp',
            name='otp',
            field=models.CharField(db_index=True, max_length=6),
        ),
        migrations.AddIndex(
            model_name='passwordresetotp',
            index=models.Index(fields=['email', 'is_used', 'expires_at'], name='offices_pas_email_b8db51_idx'),
        ),
    ]
