# Generated by Django 6.0.7 on 2026-08-07 14:27

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offices', '0005_alter_laundryoffice_subscription_tier_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubscriptionLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('customer_email', models.EmailField(blank=True, max_length=254)),
                ('event_type', models.CharField(choices=[('new', 'New Subscription'), ('renewal', 'Renewal'), ('failed', 'Payment Failed'), ('cancelled', 'Cancelled / Disabled'), ('manual', 'Manual Admin Change')], db_index=True, max_length=30)),
                ('paystack_event', models.CharField(blank=True, max_length=100)),
                ('reference', models.CharField(blank=True, db_index=True, max_length=100)),
                ('amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('tier', models.CharField(blank=True, max_length=20)),
                ('status', models.CharField(default='success', max_length=50)),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('office', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subscription_logs', to='offices.laundryoffice')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['office', '-created_at'], name='offices_sub_office__f1650c_idx'), models.Index(fields=['event_type', '-created_at'], name='offices_sub_event_t_4166a4_idx'), models.Index(fields=['reference'], name='offices_sub_referen_b097c8_idx')],
            },
        ),
    ]
