# Generated by Django 5.2.17 on 2026-08-12 00:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offices', '0006_subscriptionlog'),
    ]

    operations = [
        migrations.AddField(
            model_name='laundryoffice',
            name='subscription_expires_at',
            field=models.DateTimeField(blank=True, help_text='Date and time when current subscription tier expires', null=True),
        ),
    ]
