# Generated by Django 6.0.7 on 2026-07-22 16:44

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offices', '0004_passwordresetotp'),
        ('operations', '0006_webpushsubscription'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('name', models.CharField(max_length=255)),
                ('phone', models.CharField(blank=True, db_index=True, max_length=50, null=True)),
                ('is_whatsapp', models.BooleanField(default=False)),
                ('office', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customers', to='offices.laundryoffice')),
            ],
            options={
                'unique_together': {('office', 'phone')},
            },
        ),
        migrations.AddField(
            model_name='order',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='operations.customer'),
        ),
        migrations.AddField(
            model_name='webpushsubscription',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subscriptions', to='operations.customer'),
        ),
    ]
