# Generated by Django 6.0.7 on 2026-07-22 17:44

from django.db import migrations

def populate_customers(apps, schema_editor):
    Order = apps.get_model('operations', 'Order')
    Customer = apps.get_model('operations', 'Customer')
    WebPushSubscription = apps.get_model('operations', 'WebPushSubscription')
    
    orders = Order.objects.all()
    customer_map = {} # (office_id, phone/name) -> Customer
    
    for order in orders:
        office = order.office
        phone = order.customer_phone.strip() if order.customer_phone else None
        name = order.customer_name.strip() if order.customer_name else 'Unknown'
        is_whatsapp = order.customer_is_whatsapp
        
        # If phone is blank/null, group by name under this office branch
        if not phone:
            phone = None
            key = (office.id, f"name__{name}")
        else:
            key = (office.id, phone)
            
        if key not in customer_map:
            if phone:
                cust = Customer.objects.filter(office=office, phone=phone).first()
            else:
                cust = Customer.objects.filter(office=office, name=name, phone__isnull=True).first()
                
            if not cust:
                cust = Customer.objects.create(
                    office=office,
                    name=name,
                    phone=phone,
                    is_whatsapp=is_whatsapp
                )
            customer_map[key] = cust
            
        cust = customer_map[key]
        order.customer = cust
        order.save()
        
    for sub in WebPushSubscription.objects.all():
        phone = sub.customer_phone.strip() if sub.customer_phone else None
        if phone:
            cust = Customer.objects.filter(phone=phone).first()
            if cust:
                sub.customer = cust
                sub.save()

class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0007_customer_order_customer_webpushsubscription_customer'),
    ]

    operations = [
        migrations.RunPython(populate_customers),
    ]
