# Generated by Django 4.2.30 on 2026-07-23 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0008_auto_20260722_1744'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['office', 'created_at'], name='operations__office__67bfe0_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['office', 'due_date'], name='operations__office__a9a84b_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['office', 'current_status'], name='operations__office__40ffa8_idx'),
        ),
    ]
