# Generated by Django 6.0.7 on 2026-08-07 13:35

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offices', '0005_alter_laundryoffice_subscription_tier_and_more'),
        ('operations', '0010_supportticket'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='actionlog',
            name='action',
            field=models.CharField(db_index=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='order',
            name='customer_phone',
            field=models.CharField(db_index=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='supportticket',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('in_progress', 'In Progress'), ('resolved', 'Resolved'), ('closed', 'Closed')], db_index=True, default='pending', max_length=20),
        ),
        migrations.AddIndex(
            model_name='actionlog',
            index=models.Index(fields=['office', '-created_at'], name='operations__office__91a772_idx'),
        ),
        migrations.AddIndex(
            model_name='actionlog',
            index=models.Index(fields=['office', 'action'], name='operations__office__b07696_idx'),
        ),
        migrations.AddIndex(
            model_name='customer',
            index=models.Index(fields=['office', 'is_deleted', 'name'], name='operations__office__094a88_idx'),
        ),
        migrations.AddIndex(
            model_name='customer',
            index=models.Index(fields=['office', 'phone'], name='operations__office__e9852d_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['office', 'is_deleted', '-created_at'], name='operations__office__ad042a_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['office', 'customer'], name='operations__office__3c547f_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['office', 'customer_phone'], name='operations__office__7bfc4b_idx'),
        ),
        migrations.AddIndex(
            model_name='orderitem',
            index=models.Index(fields=['order', 'item_pricing'], name='operations__order_i_30cb37_idx'),
        ),
        migrations.AddIndex(
            model_name='supportticket',
            index=models.Index(fields=['office', 'status'], name='operations__office__f5f59f_idx'),
        ),
        migrations.AddIndex(
            model_name='supportticket',
            index=models.Index(fields=['office', '-created_at'], name='operations__office__07c2a6_idx'),
        ),
    ]
